[package]
name = "chap-8-exercises"
version = "0.1.0"
authors = ["duongphammmm <46336643+duongphammmm@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
